---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - "**/*.lock"
require: []
domains: []
reporters:
  - rubocop
  - reek
  - require_not_found
  - typecheck
require_paths: []
plugins:
  - solargraph-reek
max_files: 5000
